- name: Ansible install apache  Local to Remote
  hosts: all
  tasks:
    - name: install  apache package with playbook
      become: true
      unarchive:
        src: /root/mytest.tar
        dest: /opt/tomcat
        remote_src: yes
        
        
        

